### ISSUE TITLE
iq.com  cant  download

### ISSUE THREAD

**Issue by ali617768987** [sohail0098/webvideo-downloader#1]
![微信截图_20210720163125](https://user-images.githubusercontent.com/77323405/126420115-87439364-ef40-4d25-ba96-b78f550fe310.png)

iq.com cant find the download button  ，Maybe iqiyi just changed their algorithm. I hope you can update the new one to solve this. Because Iqiyi is a really great source of Chinese dramas.

**Comment by sohail0098** [comment]
I notice that the script is unable to work due to 2 changes on iQIYI. 
First, the script doesn't detect the dash link on iQIYI anymore. 
![image](https://user-images.githubusercontent.com/24472929/126551692-fd6b2eb4-ec86-4a19-b33b-1f874fd00d00.png)
Second, the dash data has been changed on iQIYI. All the data is now enclosed within the 'try' and 'catch' blocks. 
![image](https://user-images.githubusercontent.com/24472929/126552011-e3601515-7e51-4a75-a734-8ab96bb4ac56.png)
An easy solution is to slice off the res.json to (38, -15) to get the proper JSON format for the next parser to work.

At the moment, I am not familiar enough with JS to fix the dash link detection. I can only fix the second issue which will pop up after fixing the first issue. Although, you can still get the dash link from the browser's network tab.
I wrote a [custom downloader](https://github.com/sohail0098/iqiyi-dl) for the dash link if you are interested. You can add the dash link to it and it will download the video and save it in .mkv format.

**Comment by sohail0098** [comment]
Merged Changes from original repo. The latest change addresses both issues.
